# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=raw-cpuid
    - RUSTFLAGS='-D warnings'

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:

    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx
    #- env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
    # Windows
    - env: TARGET=x86_64-pc-windows-gnu DISABLE_TESTS=1

    # Test nightly channel
    # Linux
    - env: TARGET=i686-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    # OSX
    - env: TARGET=i686-apple-darwin DISABLE_TESTS=1
      os: osx
      rust: nightly
    - env: TARGET=x86_64-apple-darwin DISABLE_TESTS=1
      os: osx
      rust: nightly
    #- env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
    #  rust: nightly
    # Windows
    - env: TARGET=x86_64-pc-windows-gnu DISABLE_TESTS=1
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true
  #- if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then cargo install -f rustfmt-nightly; fi

script:
  #- if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then cargo fmt --all -- --check; fi
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  on:
    condition: $DEPLOY = never

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
